name: Rebuild nextstrain.org/ncov/open

on:
  # Manually triggered using `./bin/trigger open/rebuild` (or `./bin/trigger rebuild`,
  # which triggers this workflow + `./rebuild-gisaid.yml`)
  # We also allow `./bin/trigger genbank/rebuild` as currently open and GenBank are synonyms,
  # but this may change as we ingest additional sources.
  repository_dispatch:
    types:
      - rebuild
      - open/rebuild
      - genbank/rebuild

  # Manually triggered using GitHub's UI
  workflow_dispatch:

jobs:
  rebuild-open:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: setup
      run: ./bin/setup-github-workflow

    - name: rebuild
      run: ./bin/rebuild open
      env:
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        SLACK_CHANNELS: ncov-genbank-updates
